services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: advokat-app
    restart: unless-stopped
    tty: true
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./:/var/www/html
      - public_data:/var/www/html/public/storage
    networks:
      - private-net

  nginx:
    image: nginx:alpine
    container_name: nginx-server-advokat
    restart: unless-stopped
    ports:
      - "8000:80/tcp"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
      - public_data:/var/www/html/public/storage
    depends_on:
      - app
    networks:
      - private-net

volumes:
  public_data:
    driver: local

networks:
  private-net:
    external: true
